FROM mcr.microsoft.com/azure-functions/python:3.0-python3.6

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

ENV adasbus_SERVICEBUS=Endpoint=sb://adas-demo.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=48Yvu9MwOEFOazLWelPB8YqnxgKY2ubceJfXl3ZVxeQ=
ENV AzureFunctionsJobHost__Logging__Console__IsEnabled=true
COPY requirements.txt /
RUN pip install ----upgrade pip
RUN pip install -r /requirements.txt
COPY . /home/site/wwwroot